# Generated by Django 4.2.3 on 2023-07-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.DateField(default='2020-12-12'),
            preserve_default=False,
        ),
    ]
